Add new env variable for CMS backend repo
fntechgit/fnevent-tier1-default-theme pull request #1
Opened 2023-05-24 13:06 UTC by tomrndom

ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3293186&stafilter=NotComplete&fileview=grid

Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

2023-05-24 13:23 UTC, smarcet commented on src/@openeventkit/event-site/utils/envVariables.js
do we really need to shadow this entire file ?

2023-05-24 13:25 UTC, smarcet commented on src/@openeventkit/event-site/cms/config/index.js
> +config.backend.repo = getEnvVariable(CMS_BACKEND_REPO);
can we just do process.env.GATSBY_CMS_BACKEND_REPO ?

2023-05-24 13:26 UTC, smarcet requested changes
@tomrndom please review comments, also please add a .env.template file
regards

2023-05-24 14:14 UTC, smarcet approved these changes
LGTM

2023-05-24 16:44 UTC, gcutrini approved these changes
LGTM

2024-06-06 19:37 UTC, gcutrini commented
Closing, since CMS repo configuration through env variable is now natively supported in @openeventkit/event-site package.

2024-06-06 19:37 UTC, closed without merging